[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y tesseract-ocr libtesseract-dev tesseract-ocr-eng libgl1-mesa-glx libglib2.0-0 && ln -s /usr/bin/tesseract /usr/local/bin/tesseract"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure" 